# Generated by Django 2.2.1 on 2020-06-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVOES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='libro_inscripcion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='lugar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
