# Generated by Django 2.2.1 on 2020-06-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVOES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='duracion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
