# Generated by Django 2.2.1 on 2020-04-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RVOES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estatus',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='RVOES.Departamento'),
        ),
        migrations.AddField(
            model_name='notificacionregistro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVOES.Solicitud'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='departamento',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='RVOES.Departamento'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVOES.Solicitud'),
        ),
        migrations.AddField(
            model_name='cmedsuperior',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVOES.Solicitud'),
        ),
        migrations.AddField(
            model_name='cinstitucional',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVOES.Solicitud'),
        ),
        migrations.AddField(
            model_name='ccurricular',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVOES.Solicitud'),
        ),
        migrations.AddField(
            model_name='cacademica',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVOES.Solicitud'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVOES.Solicitud'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
