# Generated by Django 2.2.1 on 2020-06-08 17:22

import RVOES.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVOES', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='apellidos',
            new_name='apMatApLegal1',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='celular',
            new_name='apMatApLegal2',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='curp_rfc',
            new_name='apMatPerAut1',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='email',
            new_name='apMatPerAut2',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='dom_particular',
            new_name='apMatPerAut3',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='nombre',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apMatPerAut4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apMatPerAut5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apMatPerAut6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apPatApLegal1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apPatApLegal2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apPatPerAut1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apPatPerAut2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apPatPerAut3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apPatPerAut4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apPatPerAut5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='apPatPerAut6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='areaFormacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emailApLegal1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emailApLegal2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emailPerAut1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emailPerAut2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emailPerAut3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emailPerAut4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emailPerAut5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='emailPerAut6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estatutosVigentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='horarioDias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nivelSuperior',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomApLegal1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomApLegal2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomPerAut1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomPerAut2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomPerAut3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomPerAut4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomPerAut5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nomPerAut6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='opcion1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='opcion2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='opcion3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='perPrograma',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='poderNotApLegal1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='poderNotApLegal2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='poderNotarial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telApLegal1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telApLegal2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telPerAut1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telPerAut2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telPerAut3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telPerAut4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telPerAut5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telPerAut6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinstitucional',
            name='folio_pago',
            field=models.TextField(blank=True, default='0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cinstitucional',
            name='solicitud',
            field=models.FileField(blank=True, default='', null=True, upload_to='Archivos/Institucional', validators=[RVOES.validators.valid_extension]),
        ),
        migrations.AlterField(
            model_name='cmedsuperior',
            name='folio_pago',
            field=models.TextField(blank=True, default='0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cmedsuperior',
            name='solicitud',
            field=models.FileField(default='', upload_to='Archivos/MedSuperior', validators=[RVOES.validators.valid_extension]),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='ciclonum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='libro_inscripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='lugar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='org_cop_acta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='org_cop_identificacion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
