# Generated by Django 2.2.1 on 2020-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVOES', '0003_auto_20200601_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinstitucional',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='cmedsuperior',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cinstitucional',
            name='folio_pago',
            field=models.TextField(blank=True, default='0', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cmedsuperior',
            name='folio_pago',
            field=models.TextField(blank=True, default='0', null=True, unique=True),
        ),
    ]
