# Generated by Django 2.2.1 on 2020-06-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVOES', '0004_auto_20200603_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
