<<<<<<< HEAD
# Generated by Django 2.2.1 on 2020-08-21 04:50
=======
# Generated by Django 2.2.1 on 2020-08-11 16:33
>>>>>>> 4009ecaa3a74ba86298df81f62ab87182ca400cd

import SETyRS.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_certificado', models.CharField(max_length=20)),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('CURP', models.CharField(max_length=50)),
                ('folio_pago', models.CharField(blank=True, default='1234', max_length=50)),
                ('carrera', models.CharField(blank=True, default='Carrera', max_length=100)),
            ],
            options={
                'db_table': 'SETyRS_alumnos',
            },
        ),
        migrations.CreateModel(
            name='NotificacionAdmin',
<<<<<<< HEAD
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('visto', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(verbose_name='fecha de publicacion')),
                ('solicitud_id', models.IntegerField()),
                ('tipo_solicitud', models.IntegerField()),
                ('nivel_educativo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'SETyRS_notificaciones_admin',
            },
        ),
        migrations.CreateModel(
            name='SolicitudSinodal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.IntegerField(default=1)),
                ('institucion', models.CharField(max_length=150)),
                ('fase', models.IntegerField(default=1)),
                ('fecha', models.DateField(verbose_name='fecha de publicacion')),
                ('nivel_educativo', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_solicitud_sinodal',
            },
        ),
        migrations.CreateModel(
            name='SolicitudExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField()),
                ('institucion', models.IntegerField(default=1)),
                ('area_carrera', models.CharField(blank=True, max_length=30)),
                ('id_presidente', models.IntegerField()),
                ('id_secretario', models.IntegerField()),
                ('id_vocal', models.IntegerField()),
                ('estatus', models.IntegerField(default=1)),
                ('fase', models.IntegerField(default=1)),
                ('fecha', models.DateField(verbose_name='fecha de publicacion')),
                ('nivel_educativo', models.IntegerField(default=1)),
                ('fecha_exa', models.DateField(default='2020-06-06')),
                ('lugar_exa', models.CharField(default='Algun lugar', max_length=50)),
                ('hora_exa', models.CharField(default='12:00', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_solicitud_examen',
            },
        ),
        migrations.CreateModel(
            name='Sinodales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sinodal', models.CharField(max_length=200)),
                ('curp', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=50)),
                ('grado_academico', models.CharField(max_length=100)),
                ('estatus', models.IntegerField(default=1)),
                ('nivel_educativo', models.IntegerField(default=1)),
                ('institucion', models.CharField(default='Instituto Tecnologico de Tepic', max_length=150)),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_sinodales',
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
=======
>>>>>>> 4009ecaa3a74ba86298df81f62ab87182ca400cd
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('visto', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(verbose_name='fecha de publicacion')),
                ('solicitud_id', models.IntegerField()),
                ('tipo_solicitud', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_notificaciones_institucion',
            },
        ),
        migrations.CreateModel(
            name='Historial_admins_sinodal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(blank=True, max_length=500)),
                ('estatus', models.BooleanField(default=False)),
                ('nivel_educativo', models.IntegerField()),
                ('sinodal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Sinodales')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_historial_sinodales',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Historial_admins_examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(blank=True, max_length=500)),
                ('estatus', models.BooleanField(default=False)),
                ('nivel_educativo', models.IntegerField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudExamen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_historial_examenes',
=======
            name='SolicitudSinodal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.IntegerField(default=1)),
                ('institucion', models.CharField(max_length=150)),
                ('fase', models.IntegerField(default=1)),
                ('fecha', models.DateField(verbose_name='fecha de publicacion')),
                ('nivel_educativo', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_solicitud_sinodal',
>>>>>>> 4009ecaa3a74ba86298df81f62ab87182ca400cd
            },
        ),
        migrations.CreateModel(
            name='ArchivosSinodales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('curriculum', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/sinodales', validators=[SETyRS.validators.validate_file_extension])),
                ('cedula', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/sinodales', validators=[SETyRS.validators.validate_file_extension])),
                ('sinodal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Sinodales')),
                ('solicitud', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal')),
=======
                ('categoria', models.IntegerField()),
                ('institucion', models.IntegerField(default=1)),
                ('area_carrera', models.CharField(blank=True, max_length=30)),
                ('id_presidente', models.IntegerField()),
                ('id_secretario', models.IntegerField()),
                ('id_vocal', models.IntegerField()),
                ('estatus', models.IntegerField(default=1)),
                ('fase', models.IntegerField(default=1)),
                ('fecha', models.DateField(verbose_name='fecha de publicacion')),
                ('nivel_educativo', models.IntegerField(default=1)),
                ('fecha_exa', models.DateField(default='2020-06-06')),
                ('lugar_exa', models.CharField(default='Algun lugar', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 4009ecaa3a74ba86298df81f62ab87182ca400cd
            ],
            options={
                'db_table': 'SETyRS_documentos_sinodales',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='ArchivosAlumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_egreso', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('servicio_social', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('inscripcion_ctrl_escolar', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('recibo_pago', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('comprobante_exp', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Alumnos')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudExamen')),
            ],
            options={
                'db_table': 'SETyRS_documentos_alumnos',
            },
        ),
=======
            name='Sinodales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sinodal', models.CharField(max_length=200)),
                ('curp', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=50)),
                ('grado_academico', models.CharField(max_length=100)),
                ('estatus', models.IntegerField(default=1)),
                ('nivel_educativo', models.IntegerField(default=1)),
                ('institucion', models.CharField(default='Instituto Tecnologico de Tepic', max_length=150)),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_sinodales',
            },
        ),
        migrations.CreateModel(
            name='Historial_admins_sinodal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(blank=True, max_length=500)),
                ('estatus', models.BooleanField(default=False)),
                ('nivel_educativo', models.IntegerField()),
                ('sinodal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Sinodales')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_historial_sinodales',
            },
        ),
        migrations.CreateModel(
            name='Historial_admins_examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(blank=True, max_length=500)),
                ('estatus', models.BooleanField(default=False)),
                ('nivel_educativo', models.IntegerField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudExamen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SETyRS_historial_examenes',
            },
        ),
        migrations.CreateModel(
            name='ArchivosSinodales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/sinodales', validators=[SETyRS.validators.validate_file_extension])),
                ('cedula', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/sinodales', validators=[SETyRS.validators.validate_file_extension])),
                ('sinodal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Sinodales')),
                ('solicitud', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal')),
            ],
            options={
                'db_table': 'SETyRS_documentos_sinodales',
            },
        ),
        migrations.CreateModel(
            name='ArchivosAlumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_egreso', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('servicio_social', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('inscripcion_ctrl_escolar', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('recibo_pago', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('comprobante_exp', models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Alumnos')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudExamen')),
            ],
            options={
                'db_table': 'SETyRS_documentos_alumnos',
            },
        ),
>>>>>>> 4009ecaa3a74ba86298df81f62ab87182ca400cd
        migrations.AddField(
            model_name='alumnos',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudExamen'),
        ),
    ]
