# Generated by Django 2.2.1 on 2020-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudexamen',
            name='departamento_id',
        ),
        migrations.RemoveField(
            model_name='solicitudsinodal',
            name='departamento_id',
        ),
        migrations.AddField(
            model_name='solicitudexamen',
            name='nivel_educativo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitudsinodal',
            name='nivel_educativo',
            field=models.IntegerField(default=1),
        ),
    ]
