# Generated by Django 2.2.1 on 2020-06-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudexamen',
            name='fecha_exa',
        ),
    ]
