# Generated by Django 2.2.1 on 2020-06-19 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SETyRS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsinodal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudexamen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sinodales',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal'),
        ),
        migrations.AddField(
            model_name='sinodales',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historial_admins_sinodal',
            name='sinodal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Sinodales'),
        ),
        migrations.AddField(
            model_name='historial_admins_sinodal',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal'),
        ),
        migrations.AddField(
            model_name='historial_admins_sinodal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historial_admins_examen',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudExamen'),
        ),
        migrations.AddField(
            model_name='historial_admins_examen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivossinodales',
            name='sinodal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Sinodales'),
        ),
        migrations.AddField(
            model_name='archivossinodales',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal'),
        ),
        migrations.AddField(
            model_name='archivosalumnos',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.Alumnos'),
        ),
        migrations.AddField(
            model_name='archivosalumnos',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudExamen'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudExamen'),
        ),
    ]
