# Generated by Django 2.2.1 on 2020-04-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0002_auto_20200425_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinodales',
            name='departamento_id',
        ),
        migrations.AddField(
            model_name='sinodales',
            name='nivel_educativo',
            field=models.IntegerField(default=1),
        ),
    ]
