# Generated by Django 2.2.1 on 2020-04-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0003_auto_20200425_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudexamen',
            old_name='nombre_institucion',
            new_name='institucion',
        ),
        migrations.AddField(
            model_name='solicitudsinodal',
            name='institucion',
            field=models.CharField(default='Instituto Tecnologico de Tepic', max_length=50),
        ),
    ]
