# Generated by Django 2.2.1 on 2020-04-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0004_auto_20200425_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsinodal',
            name='institucion',
            field=models.CharField(max_length=50),
        ),
    ]
