# Generated by Django 2.2.1 on 2020-08-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0004_reglamento_interior_titulacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reglamento_interior_titulacion',
            table='SETyRS_reglamento_interior_titulacion',
        ),
    ]
