# Generated by Django 2.2.1 on 2020-04-27 01:48

import SETyRS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0005_auto_20200425_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosalumnos',
            name='certificado_egreso',
            field=models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='archivossinodales',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/sinodales', validators=[SETyRS.validators.validate_file_extension]),
        ),
    ]
