# Generated by Django 2.2.1 on 2020-04-27 01:49

import SETyRS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0006_auto_20200426_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosalumnos',
            name='servicio_social',
            field=models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='archivossinodales',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to='STyRS/archivos/sinodales', validators=[SETyRS.validators.validate_file_extension]),
        ),
    ]
