# Generated by Django 2.2.1 on 2020-04-27 01:52

import SETyRS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0007_auto_20200426_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivossinodales',
            name='cedula',
            field=models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/sinodales', validators=[SETyRS.validators.validate_file_extension]),
        ),
    ]
