# Generated by Django 2.2.1 on 2020-04-30 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0009_auto_20200430_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_admins_sinodal',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETyRS.SolicitudSinodal'),
        ),
    ]
