# Generated by Django 2.2.1 on 2020-05-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0010_auto_20200430_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacionadmin',
            old_name='departamento_id',
            new_name='nivel_educativo',
        ),
    ]
