# Generated by Django 2.2.1 on 2020-05-12 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0012_auto_20200508_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudexamen',
            old_name='id_presidente',
            new_name='presidente',
        ),
        migrations.RenameField(
            model_name='solicitudexamen',
            old_name='id_secretario',
            new_name='secretario',
        ),
        migrations.RenameField(
            model_name='solicitudexamen',
            old_name='id_vocal',
            new_name='vocal',
        ),
        migrations.RemoveField(
            model_name='solicitudexamen',
            name='cct',
        ),
        migrations.RemoveField(
            model_name='solicitudexamen',
            name='clave_institucion',
        ),
        migrations.RemoveField(
            model_name='solicitudexamen',
            name='oficio',
        ),
        migrations.AlterField(
            model_name='solicitudexamen',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UsuarioInstitucion'),
        ),
    ]
