# Generated by Django 2.2.1 on 2020-05-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0013_auto_20200512_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudexamen',
            old_name='presidente',
            new_name='presidente_id',
        ),
        migrations.RenameField(
            model_name='solicitudexamen',
            old_name='secretario',
            new_name='secretario_id',
        ),
        migrations.RenameField(
            model_name='solicitudexamen',
            old_name='vocal',
            new_name='vocal_id',
        ),
    ]
