# Generated by Django 2.2.1 on 2020-05-13 06:09

import SETyRS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0016_auto_20200512_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosalumnos',
            name='inscripcion_ctrl_escolar',
            field=models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='archivosalumnos',
            name='recibo_pago',
            field=models.FileField(blank=True, null=True, upload_to='SETyRS/archivos/alumnos', validators=[SETyRS.validators.validate_file_extension]),
        ),
    ]
