# Generated by Django 2.2.1 on 2020-05-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETyRS', '0017_auto_20200513_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_admins_examen',
            old_name='departamento_id',
            new_name='nivel_educativo',
        ),
    ]
