# Generated by Django 2.2.1 on 2020-03-16 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, null=True)),
                ('curp', models.TextField(blank=True, null=True)),
                ('celular', models.TextField(blank=True, null=True)),
                ('leida', models.CharField(blank=True, max_length=1, null=True)),
                ('fechaNotificacion', models.DateField(auto_now_add=True)),
                ('tipo_notificacion', models.CharField(default='C', max_length=2)),
                ('tipo_usuario', models.CharField(default='4', max_length=1)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
