# Generated by Django 2.2.1 on 2020-03-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_notificacionregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionregistro',
            name='nombres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
