# Generated by Django 2.2.1 on 2019-07-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('Clave_Area', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('Clave_Carrera', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Carrera', models.CharField(max_length=50)),
                ('Area_Estudio', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('Clave_CentroTrabajo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Nombre_CentroTrabajo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GradoAcademico',
            fields=[
                ('Clave_GradoAcademico', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('Clave_Institucion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Nombre_Institucion', models.CharField(max_length=50)),
                ('estatus', models.CharField(max_length=15)),
                ('Clave_CentroTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.CentroTrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('Clave_Modalidad', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('Clave_Municipio', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('Clave_Periodo', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RVOE',
            fields=[
                ('IdRVOE', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Clave_Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.Carrera')),
                ('Clave_GradoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.GradoAcademico')),
                ('Clave_Institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.Institucion')),
                ('Clave_Modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.Modalidad')),
                ('Clave_Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.Periodos')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('Clave_Localidad', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=70)),
                ('Clave_Municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=200)),
                ('Clave_Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.Carrera')),
                ('Clave_Institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.Institucion')),
                ('areaInteres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.AreaInteres')),
            ],
        ),
        migrations.CreateModel(
            name='DatosEstadisticos',
            fields=[
                ('FechaRegistro', models.DateTimeField(primary_key=True, serialize=False)),
                ('totalAlumnos', models.BigIntegerField()),
                ('totalAlumnosFemenino', models.BigIntegerField()),
                ('totalAlumnosMasculino', models.BigIntegerField()),
                ('totalDocentes', models.BigIntegerField()),
                ('IdRVOE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.RVOE')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionCentroTrabajo',
            fields=[
                ('Clave_CentroTrabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SigApp.CentroTrabajo')),
                ('direccion', models.CharField(max_length=250)),
                ('Localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.Localidad')),
            ],
        ),
    ]
