# Generated by Django 2.2.1 on 2019-07-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecarrera',
            name='areaInteres',
        ),
    ]
