# Generated by Django 2.2.1 on 2019-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0004_auto_20190707_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestadisticos',
            name='alumnosIndigenasF',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosestadisticos',
            name='alumnosIndigenasM',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosestadisticos',
            name='totalAdministrativos',
            field=models.BigIntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosestadisticos',
            name='totalAlumnosIndigenas',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='Dominio_Institucion',
            field=models.CharField(default='Publica', max_length=7),
            preserve_default=False,
        ),
    ]
