# Generated by Django 2.2.1 on 2019-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0005_auto_20190718_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosestadisticos',
            name='totalAdministrativos',
        ),
        migrations.RemoveField(
            model_name='datosestadisticos',
            name='totalDocentes',
        ),
        migrations.AddField(
            model_name='institucion',
            name='totalAdministrativos',
            field=models.BigIntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='totalDocentes',
            field=models.BigIntegerField(default=57),
            preserve_default=False,
        ),
    ]
