# Generated by Django 2.2.2 on 2019-08-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0006_auto_20190722_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='ImagenNo1',
            field=models.ImageField(blank=True, upload_to='imagenes_instituciones_perfil'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='ImagenNo2',
            field=models.ImageField(blank=True, upload_to='imagenes_instituciones_perfil'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='ImagenNo3',
            field=models.ImageField(blank=True, upload_to='imagenes_instituciones_perfil'),
        ),
    ]
