# Generated by Django 2.2.2 on 2019-08-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0007_auto_20190820_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='Director_Institucion',
            field=models.CharField(default='Albino Test', max_length=100),
            preserve_default=False,
        ),
    ]
