# Generated by Django 2.2.1 on 2019-08-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0008_institucion_director_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnosPorGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnosPrimerGrado', models.IntegerField()),
                ('alumnosSegundoGrado', models.IntegerField()),
                ('alumnosTercerGrado', models.IntegerField()),
                ('alumnosCuartoGrado', models.IntegerField()),
                ('alumnosQuintoGrado', models.IntegerField()),
                ('alumnosSextoGrado', models.IntegerField()),
                ('IdRVOE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.RVOE')),
            ],
        ),
    ]
