# Generated by Django 2.2.1 on 2019-08-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0010_auto_20190827_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnosporgrado',
            name='alumnosIPrimerGradoHombres',
        ),
        migrations.RemoveField(
            model_name='alumnosporgrado',
            name='alumnosIPrimerGradoMujeres',
        ),
        migrations.RemoveField(
            model_name='alumnosporgrado',
            name='alumnosPrimerGrado',
        ),
        migrations.RemoveField(
            model_name='alumnosporgrado',
            name='alumnosPrimerGradoHombres',
        ),
        migrations.RemoveField(
            model_name='alumnosporgrado',
            name='alumnosPrimerGradoMujeres',
        ),
    ]
