# Generated by Django 2.2.2 on 2019-09-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0013_auto_20190911_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='ImagenNo1',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_instituciones_perfil'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='ImagenNo2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_instituciones_perfil'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='ImagenNo3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_instituciones_perfil'),
        ),
    ]
