# Generated by Django 2.2.1 on 2019-11-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0016_escuela_escuuelac'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaC',
            fields=[
                ('ClaveEscuela', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('NombreEscuela', models.CharField(max_length=200)),
                ('EstatusEscuela', models.CharField(max_length=200)),
                ('Calle', models.CharField(max_length=200)),
                ('Municipio', models.CharField(max_length=200)),
                ('Localidad', models.CharField(max_length=200)),
                ('CodPostal', models.CharField(max_length=200)),
                ('Latitud', models.CharField(max_length=200)),
                ('Longitud', models.CharField(max_length=200)),
                ('Dominio', models.CharField(max_length=200)),
                ('nombreDirector', models.CharField(max_length=200)),
                ('ApellidoP_Director', models.CharField(max_length=200)),
                ('ApellidoM_Director', models.CharField(max_length=200)),
                ('Telefono_Director', models.CharField(max_length=200)),
                ('Celuar_Director', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Nivel', models.CharField(max_length=200)),
                ('TipoServicio', models.CharField(max_length=200)),
            ],
        ),
    ]
