# Generated by Django 2.2.2 on 2019-11-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0017_auto_20191110_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('IdEscuela', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('NombreEscuela', models.CharField(max_length=50)),
                ('RazonSocial', models.CharField(max_length=50)),
                ('Dominio', models.CharField(max_length=50)),
                ('Personal', models.CharField(max_length=50)),
                ('CodPostal', models.CharField(max_length=50)),
                ('ClaveM', models.CharField(max_length=50)),
                ('Municipio', models.CharField(max_length=50)),
                ('ClaveL', models.CharField(max_length=50)),
                ('Localidad', models.CharField(max_length=50)),
                ('Latitud', models.CharField(max_length=50)),
                ('Longitud', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estadisticosNuevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalAlumnos', models.IntegerField()),
                ('TotalPrimero', models.IntegerField()),
                ('TotalSegundo', models.IntegerField()),
                ('TotalTercero', models.IntegerField()),
                ('TotalCuarto', models.IntegerField()),
                ('TotalQuinto', models.IntegerField()),
                ('TotalSexto', models.IntegerField()),
                ('TotalHombres', models.IntegerField()),
                ('TotalMujeres', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EscuuelaC',
        ),
        migrations.AddField(
            model_name='escuelac',
            name='ImagenNo1',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_instituciones_perfil'),
        ),
        migrations.AddField(
            model_name='escuelac',
            name='ImagenNo2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_instituciones_perfil'),
        ),
        migrations.AddField(
            model_name='escuelac',
            name='ImagenNo3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_instituciones_perfil'),
        ),
        migrations.AddField(
            model_name='estadisticosnuevo',
            name='ClaveEscuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.EscuelaC', unique=True),
        ),
    ]
