# Generated by Django 2.2.2 on 2019-11-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0018_auto_20191122_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estadisticosNuevo',
        ),
    ]
