# Generated by Django 2.2.2 on 2019-11-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0019_delete_estadisticosnuevo'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadisticosNuevo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalAlumnos', models.IntegerField()),
                ('TotalPrimero', models.IntegerField()),
                ('TotalSegundo', models.IntegerField()),
                ('TotalTercero', models.IntegerField()),
                ('TotalCuarto', models.IntegerField()),
                ('TotalQuinto', models.IntegerField()),
                ('TotalSexto', models.IntegerField()),
                ('TotalHombres', models.IntegerField()),
                ('TotalMujeres', models.IntegerField()),
                ('ClaveEscuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.EscuelaC', unique=True)),
            ],
        ),
    ]
