# Generated by Django 2.2.1 on 2019-11-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0021_rvoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rvoes',
            old_name='TotalCauarto',
            new_name='TotalCuarto',
        ),
    ]
