# Generated by Django 2.2.1 on 2019-11-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0022_auto_20191123_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvoes',
            name='ClaveEscuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.EscuelaC'),
        ),
    ]
