# Generated by Django 2.2.1 on 2019-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0023_auto_20191123_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvoes',
            name='ClaveEscuela',
            field=models.CharField(max_length=100),
        ),
    ]
