# Generated by Django 2.2.1 on 2019-11-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0024_auto_20191123_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RVOES',
        ),
    ]
