# Generated by Django 2.2.1 on 2019-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0025_delete_rvoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVOES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaveEscuela', models.CharField(max_length=100)),
                ('NombreCarrera', models.CharField(max_length=200)),
                ('TotalAlumnos', models.IntegerField()),
                ('TotalPrimero', models.IntegerField()),
                ('TotalSegundo', models.IntegerField()),
                ('TotalTercero', models.IntegerField()),
                ('TotalCuarto', models.IntegerField()),
                ('TotalQuinto', models.IntegerField()),
                ('TotalSexto', models.IntegerField()),
                ('TotalHombres', models.IntegerField()),
                ('TotalMujeres', models.IntegerField()),
                ('Tipo', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=100)),
            ],
        ),
    ]
