# Generated by Django 2.2.1 on 2019-11-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0026_rvoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvoes',
            name='ClaveCarrera',
            field=models.CharField(default=1566, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rvoes',
            name='Modalidad',
            field=models.CharField(default='Escolarizada', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rvoes',
            name='Periodos',
            field=models.CharField(default='Semestral', max_length=25),
            preserve_default=False,
        ),
    ]
