# Generated by Django 2.2.1 on 2019-11-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0027_auto_20191125_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvoes',
            name='ClaveEscuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.EscuelaC'),
        ),
    ]
