# Generated by Django 2.2.1 on 2019-11-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0028_auto_20191125_0114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RVOES',
        ),
    ]
