# Generated by Django 2.2.1 on 2019-11-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0029_delete_rvoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVOES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCarrera', models.CharField(max_length=200)),
                ('TotalAlumnos', models.IntegerField()),
                ('TotalPrimero', models.IntegerField()),
                ('TotalSegundo', models.IntegerField()),
                ('TotalTercero', models.IntegerField()),
                ('TotalCuarto', models.IntegerField()),
                ('TotalQuinto', models.IntegerField()),
                ('TotalSexto', models.IntegerField()),
                ('TotalHombres', models.IntegerField()),
                ('TotalMujeres', models.IntegerField()),
                ('Tipo', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=100)),
                ('ClaveCarrera', models.CharField(max_length=30)),
                ('Modalidad', models.CharField(max_length=25)),
                ('Periodos', models.CharField(max_length=25)),
                ('ClaveEscuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SigApp.EscuelaC')),
            ],
        ),
    ]
