# Generated by Django 2.2.1 on 2020-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0030_rvoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrotrabajo',
            name='Nombre_CentroTrabajo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='Nombre_Institucion',
            field=models.CharField(max_length=100),
        ),
    ]
