# Generated by Django 2.2.1 on 2020-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0031_auto_20200506_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datostemporal',
            name='clave_centrotrabajo_temp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datostemporal',
            name='direccion_temp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datostemporal',
            name='director_temp',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datostemporal',
            name='localidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datostemporal',
            name='municipio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datostemporal',
            name='nombre_institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datostemporal',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
