# Generated by Django 2.2.1 on 2020-05-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0033_historialmod'),
    ]

    operations = [
        migrations.AddField(
            model_name='datostemporal',
            name='usuario_mod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
