# Generated by Django 2.2.1 on 2020-05-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0034_datostemporal_usuario_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmod',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
