# Generated by Django 2.2.1 on 2020-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0035_historialmod_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmod',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historialmod',
            name='tipo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
