# Generated by Django 2.2.1 on 2020-06-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0036_auto_20200528_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvoes',
            name='modificando',
            field=models.BooleanField(default=False),
        ),
    ]
