# Generated by Django 2.2.1 on 2020-06-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0037_rvoes_modificando'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTemporalEstadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaveEscuela_temp', models.CharField(max_length=200)),
                ('NombreCarreraA_temp', models.CharField(max_length=200)),
                ('TotalAlumnos_temp', models.IntegerField()),
                ('TotalPrimero_temp', models.IntegerField()),
                ('TotalSegundo_temp', models.IntegerField()),
                ('TotalTercero_temp', models.IntegerField()),
                ('TotalCuarto_temp', models.IntegerField()),
                ('TotalQuinto_temp', models.IntegerField()),
                ('TotalSexto_temp', models.IntegerField()),
                ('TotalHombres_temp', models.IntegerField()),
                ('TotalMujeres_temp', models.IntegerField()),
                ('Tipo_temp', models.CharField(max_length=50)),
                ('Area_temp', models.CharField(max_length=100)),
                ('ClaveCarrera_temp', models.CharField(max_length=30)),
                ('Modalidad_temp', models.CharField(max_length=25)),
                ('Periodos_temp', models.CharField(max_length=25)),
                ('modificando', models.BooleanField()),
            ],
        ),
    ]
