# Generated by Django 2.2.1 on 2020-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0039_auto_20200609_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialModEstadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechamod', models.DateTimeField()),
                ('tipo', models.BooleanField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario_dep', models.CharField(max_length=200)),
                ('usuario_mod', models.CharField(max_length=200)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('ClaveEscuela_prev', models.CharField(max_length=200)),
                ('NombreCarrera_prev', models.CharField(max_length=200)),
                ('TotalAlumnos_prev', models.IntegerField()),
                ('TotalPrimero_prev', models.IntegerField()),
                ('TotalSegundo_prev', models.IntegerField()),
                ('TotalTercero_prev', models.IntegerField()),
                ('TotalCuarto_prev', models.IntegerField()),
                ('TotalQuinto_prev', models.IntegerField()),
                ('TotalSexto_prev', models.IntegerField()),
                ('TotalHombres_prev', models.IntegerField()),
                ('TotalMujeres_prev', models.IntegerField()),
                ('Tipo_prev', models.CharField(max_length=50)),
                ('Area_prev', models.CharField(blank=True, max_length=100, null=True)),
                ('ClaveCarrera_prev', models.CharField(max_length=30)),
                ('Modalidad_prev', models.CharField(max_length=25)),
                ('Periodos_prev', models.CharField(max_length=25)),
                ('ClaveEscuela_new', models.CharField(max_length=200)),
                ('NombreCarreraA_new', models.CharField(max_length=200)),
                ('TotalAlumnos_new', models.IntegerField()),
                ('TotalPrimero_new', models.IntegerField()),
                ('TotalSegundo_new', models.IntegerField()),
                ('TotalTercero_new', models.IntegerField()),
                ('TotalCuarto_new', models.IntegerField()),
                ('TotalQuinto_new', models.IntegerField()),
                ('TotalSexto_new', models.IntegerField()),
                ('TotalHombres_new', models.IntegerField()),
                ('TotalMujeres_new', models.IntegerField()),
                ('Tipo_new', models.CharField(max_length=50)),
                ('Area_new', models.CharField(blank=True, max_length=100, null=True)),
                ('ClaveCarrera_new', models.CharField(max_length=30)),
                ('Modalidad_new', models.CharField(max_length=25)),
                ('Periodos_new', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='datostemporalestadistica',
            name='Area_temp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
