# Generated by Django 2.2.1 on 2020-06-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0040_auto_20200610_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmodestadistica',
            old_name='NombreCarreraA_new',
            new_name='NombreCarrera_new',
        ),
    ]
