# Generated by Django 2.2.1 on 2020-06-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SigApp', '0041_auto_20200610_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmodestadistica',
            name='TotalAlumnos_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialmodestadistica',
            name='TotalAlumnos_prev',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
