# Generated by Django 2.2.1 on 2020-04-27 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_digitales/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='localidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='UsuarioInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.TextField(blank=True, null=True)),
                ('nombredirector', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=1, null=True)),
                ('nivel_educativo', models.TextField(blank=True, null=True)),
                ('id_usuariobase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
