# Generated by Django 2.2.1 on 2020-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200426_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioinstitucion',
            name='estatus',
        ),
        migrations.AddField(
            model_name='usuarioinstitucion',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioinstitucion',
            name='cct',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioinstitucion',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
