# Generated by Django 2.2.1 on 2020-05-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200430_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioinstitucion',
            name='modalidad',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
    ]
