# Generated by Django 2.2.1 on 2020-05-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_usuarioinstitucion_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioinstitucion',
            name='cct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SigApp.EscuelaC'),
        ),
    ]
