from django.db import models

# Modelo de alumno
class Alumno(models.Model):
    id_alumno = models.IntegerField(primary_key= True)
    nombre_escuela = models.CharField(max_length=150)
    cct = models.CharField(max_length=50) 
    nombre_alumno = models.CharField(max_length=150) 
    num_matricula = models.CharField(max_length=150)
    curp_alumno = models.CharField(max_length=20) 
    mat1p1 = models.DecimalField(max_digits=8, decimal_places=2, null=True)
    mat1p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    mat1pr = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_mat1 = models.CharField(max_length=20, null=True) 
    q1p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    q1p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True)
    q1p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True)
    prom_q1 = models.CharField(max_length=20, null=True)
    evp1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    evp2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    evp3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ev1 = models.CharField(max_length=20, null=True) 
    icsp1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    icsp2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    icsp3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_icsp = models.CharField(max_length=20, null=True)  
    tlrp1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    tlrp2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    tlrp3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_tlr1 = models.CharField(max_length=20, null=True) 
    lae1p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lae1p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lae1p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_lae1 = models.CharField(max_length=20, null=True) 
    app1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    app2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    app3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ap1 = models.CharField(max_length=20, null=True) 
    prom_general_1 = models.CharField(max_length=20, null=True) 
    periodo2 = models.CharField(max_length=20, null=True) 
    semestre2 = models.CharField(max_length=20, null=True) 
    mat2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    mat2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    mat2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_mat2 = models.CharField(max_length=20, null=True) 
    q2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    q2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    q2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_q2 = models.CharField(max_length=20, null=True) 
    ev2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ev2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ev2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ev2 = models.CharField(max_length=20, null=True) 
    hmi1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    hmi2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    hmi3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_hmi = models.CharField(max_length=20, null=True) 
    tlr2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    tlr2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    tlr2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_tlr2 = models.CharField(max_length=20, null=True) 
    lae2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lae2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lae2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_lae2 = models.CharField(max_length=20, null=True) 
    ap2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ap2 = models.CharField(max_length=20, null=True) 
    promedio_general_2 = models.CharField(max_length=20, null=True) 
    ciclo_escolar_2 = models.CharField(max_length=20, null=True) 
    periodo_3 = models.CharField(max_length=20, null=True) 
    semestre_3 = models.CharField(max_length=20, null=True) 
    mat3p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    mat3p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    mat3p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_mat3 = models.CharField(max_length=20, null=True) 
    bio1p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    bio1p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    bio1p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_bio1 = models.CharField(max_length=20, null=True) 
    fis1p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    fis1p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    fis1p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_fis1 = models.CharField(max_length=20, null=True) 
    hmiip1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    hmiip2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    hmiip3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_hmii = models.CharField(max_length=20, null=True) 
    litip1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    litip2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    litip3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_liti = models.CharField(max_length=20, null=True) 
    lae3p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lae3p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lae3p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_lae3 = models.CharField(max_length=20, null=True) 
    dc1p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    dc1p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    dc1p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_dc1 = models.CharField(max_length=20, null=True) 
    ap3p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap3p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap3p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ap3 = models.CharField(max_length=20, null=True) 
    promedio_general_3 = models.CharField(max_length=20, null=True)  
    periodo_4 = models.CharField(max_length=20, null=True) 
    semestre_4 = models.CharField(max_length=20, null=True) 
    mat4p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    mat4p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    mat4p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_mat4 = models.CharField(max_length=20, null=True) 
    bio2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    bio2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    bio2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_bio2 = models.CharField(max_length=20, null=True) 
    fis2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    fis2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    fis2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_fis2 = models.CharField(max_length=20, null=True) 
    esmp1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    esmp2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    esmp3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_esm = models.CharField(max_length=20, null=True) 
    lit2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lit2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lit2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_lit2 = models.CharField(max_length=20, null=True) 
    lae4p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lae4p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    lae4p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_lae4 = models.CharField(max_length=20, null=True) 
    dc2p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    dc2p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    dc2p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_dc2 = models.CharField(max_length=20, null=True) 
    ap4p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap4p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap4p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ap4 = models.CharField(max_length=20, null=True) 
    promedio_general_4 = models.CharField(max_length=20, null=True) 
    periodo_5 = models.CharField(max_length=20, null=True) 
    semestre_5 = models.CharField(max_length=20, null=True) 
    geog1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    geog2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    geog3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_geog = models.CharField(max_length=20, null=True) 
    huc1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    huc2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    huc3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_huc = models.CharField(max_length=20, null=True) 
    derech1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    derech2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    derech3  = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_derech = models.CharField(max_length=20, null=True) 
    cc1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    cc2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    cc3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_cc = models.CharField(max_length=20, null=True) 
    cs1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    cs2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    cs3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_cs = models.CharField(max_length=20, null=True) 
    proyes1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    proyes2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    proyes3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_proyes = models.CharField(max_length=20, null=True) 
    dc3p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    dc3p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    dc3p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_dc3 = models.CharField(max_length=20, null=True) 
    ap5p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap5p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap5p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ap5 = models.CharField(max_length=20, null=True) 
    promedio_general_5 = models.CharField(max_length=20, null=True) 
    periodo_6 = models.CharField(max_length=20, null=True) 
    semestre_6 = models.CharField(max_length=20, null=True) 
    filos1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    filos2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    filos3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_filos = models.CharField(max_length=20, null=True) 
    ema1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ema2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ema3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ema = models.CharField(max_length=20, null=True) 
    met_inv1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True)  
    met_inv2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    met_inv3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_met_inv = models.CharField(max_length=20, null=True) 
    derech16 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    derech27 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    derech38 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_derech2 = models.CharField(max_length=20, null=True) 
    cc19 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    cc210 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    cc311  = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_cc2 = models.CharField(max_length=20, null=True) 
    cs112 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    cs213 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    cs314 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_cs2 = models.CharField(max_length=20, null=True) 
    proyes115 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    proyes216 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    proyes317 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_proyes2 = models.CharField(max_length=20, null=True) 
    dc3p118 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    dc3p219 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    dc3p320 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_dc4 = models.CharField(max_length=20, null=True) 
    ap6p1 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap6p2 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    ap6p3 = models.DecimalField(max_digits= 8,decimal_places=2, null=True) 
    prom_ap6 = models.CharField(max_length=20, null=True) 
    promedio_general_6 = models.CharField(max_length=20, null=True)
    promedio_final = models.DecimalField(max_digits= 8,decimal_places=2, null=True)
    email = models.EmailField(max_length=254, null=True) #models.CharField(max_length=150)
    tel_fijo = models.CharField(max_length=150, null=True)
    tel_celular = models.CharField(max_length=150, null=True)
    calle = models.CharField(max_length=150, null=True) #TODO: Eliminar
    colonia = models.CharField(max_length=150, null=True) #TODO: Eliminar
    num_int = models.CharField(max_length=150, null=True) #TODO: Eliminar
    num_ext = models.CharField(max_length=150, null=True) #TODO: Eliminar
    semestre = models.CharField(max_length=150)
    tipo_secundaria = models.CharField(max_length=150, null=True)
    acta_nacimiento = models.FileField(upload_to='Archivos/TBC', null=True)
    curp_archivo = models.FileField(upload_to='Archivos/TBC', null=True)
    certificado_secundaria = models.FileField(upload_to='Archivos/TBC', null=True)

class Curso(models.Model):
    id_curso = models.IntegerField(primary_key= True)
    clave_curso = models.CharField(max_length=150)
    nombre_curso = models.CharField(max_length=150)
    semestre = models.IntegerField()
    descripcion = models.CharField(max_length=150)
    creditos = models.IntegerField()

class Docente_curso(models.Model):
    id_dc = models.AutoField(primary_key= True)
    #id_curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    #id_docente = models.ForeignKey(Docente, on_delete=models.CASCADE)
    id_curso = models.IntegerField()
    id_docente = models.IntegerField()

class Alumno_curso(models.Model):
    id_ac = models.AutoField(primary_key= True)
    id_dc = models.IntegerField()
    id_alumno = models.IntegerField()
    #TODO: Ver porqué no me elimina este registro al querer eliminar un alumno 
    #Debido a esto comenté las foreignKey para que funcionara
    #id_dc = models.ForeignKey(Docente_curso, on_delete=models.CASCADE)
    #id_alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)


class Actividad_docente(models.Model):
    id_actividad =  models.IntegerField(primary_key= True)#models.CharField(primary_key=True, max_length=300)
    nombre_actividad = models.CharField(max_length=400)
    unidad = models.IntegerField()
    tipo_actividad = models.CharField(max_length=200)
    tema = models.CharField(max_length=200)
    subtema = models.CharField(max_length=200)
    objetivo = models.CharField(max_length=500)
    recurso = models.FileField(upload_to='Archivos/TBC')
    rubrica = models.FileField(upload_to='Archivos/TBC')
    valor_parcial = models.IntegerField()
    fecha_hora_limite = models.CharField(max_length=50) 
    fechaAct = models.CharField(max_length=200)
    id_docente = models.IntegerField()
    id_curso = models.IntegerField()

class Entrega_actividad(models.Model):
    id_entrega = models.AutoField(primary_key= True)
    nombre_actividad = models.CharField(max_length=400)
    calificacion = models.DecimalField(max_digits= 8,decimal_places=2, null=True)
    retroalimentacion = models.CharField(max_length=500, null=True)
    archivo =  models.CharField(max_length=500) #models.FileField(upload_to='Archivos/TBC')
    fecha_hora_subida = models.CharField(max_length=50)
    id_alumno = models.IntegerField()
    id_actividad = models.IntegerField()
    url = models.CharField(max_length=300)
    comentario = models.CharField(max_length=500)
    calificada = models.BooleanField()
    entregada = models.BooleanField()
    totalO = models.IntegerField()
    totalO = models.CharField(max_length=500)
    
#Modelo de semestre
class Semestre(models.Model):
    id_semestre = models.AutoField(primary_key=True)
    nombre_semestre = models.CharField(max_length=10)
'''
class Modulo(models.Model):
    id_modulo = models.CharField(primary_key=True, max_length=30)
    id_semestre = models.ForeignKey(Semestre,on_delete=models.CASCADE)
    nombre_modulo = models.CharField(max_length=100)
    objetivo_modulo = models.CharField(max_length=400)
    competencias_modulo = models.CharField(max_length=500)
    programa_modulo = models.FileField(upload_to='programas/TBC')
'''
#Modelo de Area Disciplinar
class Area_disciplinar(models.Model):
    id_areadisciplinar = models.IntegerField(primary_key=True)
    nombre_areadisciplinar = models.CharField(max_length=200)

#Modelo de modulo
class Modulo(models.Model):
    id_modulo = models.AutoField(primary_key=True)
    nombre_modulo = models.CharField(max_length=150)
    pdf_modulo = models.FileField(upload_to='Archivos/modulos')
    semestre_modulo = models.ForeignKey(Semestre, on_delete=models.CASCADE)
    areadisciplinar_modulo = models.ForeignKey(Area_disciplinar, on_delete=models.CASCADE)
    fecha_alta_modulo = models.DateField(auto_now=True)
    creditos_modulo = models.IntegerField()  

#Modelo de unidades de modulo
class Unidad_modulo(models.Model):
    id_unidad = models.AutoField(primary_key=True)
    id_modulo_unidad = models.ForeignKey(Modulo, on_delete=models.CASCADE)
    nombre_unidad = models.CharField(max_length=500)
    proposito_unidad = models.CharField(max_length=800)

#Modelo de aprendizaje esperado
class Aprendizaje_esperado_modulo(models.Model):
    id = models.AutoField(primary_key=True)
    unidad_aprendizaje_esperado = models.ForeignKey(Unidad_modulo, on_delete=models.CASCADE)
    modulo_aprendizaje_esperado = models.ForeignKey(Modulo, on_delete=models.CASCADE)
    aprendizaje_esperado = models.CharField(max_length=700)

class Archivo(models.Model):
    id_archivo = models.IntegerField(primary_key= True)
    nombre_archivo = models.CharField(max_length=500)
    archivo = models.FileField(upload_to='TBC/archivos', blank=True, null=True) #models.CharField(max_length=500, null=True)
    descripcion = models.CharField(max_length=500, null=True)
    tipo_archivo = models.CharField(max_length=100)
    id_actividad = models.IntegerField(null=True)
    url = models.CharField(max_length=500)
    id_alumno = models.IntegerField(null=True)
    id_docente = models.IntegerField(null=True)

class Notificacion_act(models.Model):
    id_notificacion = models.AutoField(primary_key= True)
    id_dc = models.IntegerField()
    id_actividad = models.IntegerField()
    mensaje = models.CharField(max_length=500)
    tipo = models.IntegerField()

class Notificacion_act_alumno(models.Model):
    id_notificacion_alumno = models.AutoField(primary_key= True)
    id_alumno = models.IntegerField()
    status = models.IntegerField()
    id_notificacion = models.CharField(max_length=500)
    id_dc = models.IntegerField()

class Notificacion_act_docente(models.Model):
    id_notificacion_docente = models.AutoField(primary_key= True)
    id_docente = models.IntegerField()
    status = models.IntegerField()
    id_notificacion = models.CharField(max_length=500)
    id_alumno = models.IntegerField()
    id_dc = models.IntegerField()
    tipo = models.IntegerField()

class Notificacion_mod(models.Model):
    id_notificacion = models.AutoField(primary_key= True)
    id_curso = models.IntegerField()
    mensaje = models.CharField(max_length=500)
    tipo = models.IntegerField()

class Notificacion_mod_docente(models.Model):
    id_notificacion_mod_doc = models.AutoField(primary_key= True)
    id_docente = models.IntegerField()
    status = models.IntegerField()
    id_notificacion = models.IntegerField()
    fecha_hora = models.CharField(max_length=500)

class Asistencia(models.Model):
    id_asistencia = models.AutoField(primary_key = True)
    cct  = models.CharField(max_length = 200)
    fecha = models.CharField(max_length = 100)
    semestre = models.IntegerField()
    id_alumno = models.IntegerField()
    id_dc = models.IntegerField()
    asistencia = models.BooleanField()
    retardo = models.BooleanField()
    justificacion = models.BooleanField()
    falta = models.BooleanField()

#Modelo de docente
class Docente(models.Model):
    id_docente = models.IntegerField(primary_key= True)
    nombres_docente = models.CharField(max_length=150)
    apellidos_docente = models.CharField(max_length=150, null=True)
    edad_docente = models.IntegerField()
    email = models.CharField(max_length=150)
    clave_docente = models.CharField(max_length=150)
    cct = models.CharField(max_length=50) 
    curp_docente =  models.CharField(max_length=20)
    rfc_docente =  models.CharField(max_length=30)
    tel_fijo = models.CharField(max_length=150, null=True)
    tel_cel = models.CharField(max_length=150)
    nombre_escuela = models.CharField(max_length=150)
    areadisciplinar_docente = models.ForeignKey(Area_disciplinar, on_delete=models.CASCADE, null=True)
    domicilio = models.CharField(max_length=500, null=True)
    num_empleado = models.CharField(max_length=150, null=True)
    curriculum = models.FileField(upload_to='Archivos/TBC')
    perfil_profesional = models.CharField(max_length=200, null=True)
    maximo_grado = models.CharField(max_length=200, null=True)
    localidad = models.CharField(max_length=200, null=True)
