# Generated by Django 2.2.1 on 2020-04-07 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RVOES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanteSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True)),
                ('curp_rfc', models.CharField(blank=True, max_length=18, null=True)),
                ('calle', models.TextField(blank=True, null=True)),
                ('noexterior', models.IntegerField(blank=True, null=True)),
                ('nointerior', models.IntegerField(blank=True, null=True)),
                ('codigopostal', models.IntegerField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('colonia', models.TextField(blank=True, null=True)),
                ('celular', models.TextField(blank=True, null=True)),
                ('email', models.TextField(unique=True)),
                ('leida', models.CharField(default='0', max_length=1)),
                ('tipo_usuario', models.CharField(default='4', max_length=1)),
                ('tipo_persona', models.CharField(default='1', max_length=1)),
                ('jefe', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RVOES.Departamento')),
            ],
        ),
    ]
