# Generated by Django 2.2.1 on 2020-03-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitantesc',
            name='password',
        ),
    ]
