# Generated by Django 2.2.1 on 2020-04-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='formatoPDF/')),
            ],
        ),
    ]
