# Generated by Django 2.2.1 on 2020-03-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0002_remove_visitantesc_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantesc',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitantesc',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitantesc',
            name='password',
            field=models.TextField(blank=True),
        ),
    ]
