# Generated by Django 2.2.1 on 2020-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0002_configuracionpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantesc',
            name='inst_cct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitantesc',
            name='inst_nombredirector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
