# Generated by Django 2.2.1 on 2020-03-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0003_auto_20200318_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantesc',
            name='leida',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
