# Generated by Django 2.2.1 on 2020-04-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0003_auto_20200420_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitantesc',
            name='inst_cct',
        ),
        migrations.RemoveField(
            model_name='visitantesc',
            name='inst_nombredirector',
        ),
    ]
