# Generated by Django 2.2.1 on 2020-04-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0005_auto_20200423_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitantesc',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='visitantesc',
            name='jefe',
        ),
        migrations.AddField(
            model_name='visitantesc',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='visitantesc',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitantesc',
            name='tipo_usuario',
            field=models.CharField(default='5', max_length=1),
        ),
    ]
