# Generated by Django 2.2.1 on 2020-05-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitante', '0006_auto_20200424_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantesc',
            name='modalidad',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
    ]
